### PR TITLE
This commit adds support for the stop_sequence parameter

### PR DESCRIPTION
**Pull request by LostRuins**
This commit finally adds support for the `stop_sequence` parameter for the text generation payload in Horde. The `stop_sequence` is an array of stopping strings that indicates to the backend when generation should be prematurely halted. As it is already integrated into Kobold as part of the submitted payload, no modification to the scribe/worker should be necessary. 

Do review, thanks!

### CODE REVIEW

**Comment by db0** [comment]
Please put a reasonable max chars to the string, to avoid people sending trolling payloads

**Comment by LostRuins** [comment]
@db0 How about this? This rejects requests with more than 16 stop sequences, or with a stop sequence exceeding 512 characters.

**Comment by db0** [comment]
OK so theoretically someone could send 16x512 stop sequences? Is that something someone reasonable might do?

**Comment by LostRuins** [comment]
Modified the PR. 

This counts by total stop sequence length instead, reducing the theoretical maximum from about 8k to 2k characters, a more fair approach. Averaged across the 16 seq limit, that is averaged 125 chars per sequence, while allowing some to be longer if needed.

**Pull request merged**
