### PR TITLE
docker image build

### PR DESCRIPTION
**Pull request by motolies**
Create a Docker image. 
The server.py has been modified to accept docker environment variables in uppercase.

It would be nice to add a github action in the future.

### CODE REVIEW

**Comment by db0** [comment]
Note, the AI Horde is designed to run on multiple ports in the same VM.  How is this handled here?

**Comment by motolies** [comment]
제가 현재 알고 있는 포트는 7001번 하나 입니다. 
추가 포트를 알려주시면 추가하고 테스트 하겠습니다.

**Comment by db0** [comment]
The port is open ended. It can be changed with `--port`. How many one opens depends on how many CPU they have available. I am not good with docker tbh so I don't know what the best approach should be here. How do you envision fully utilizing a VM with multiple CPUs?

**Comment by motolies** [comment]
If there is only one inbound port that can be called by ai-horde, but it can be changed, you can modify the docker file to handle it as an environment variable. 
If ai-horde has multiple inbound ports, you need to know them all to be able to handle them.

How many ports is the server listening on?

**Comment by db0** [comment]
The AI Horde is only listening to whichever port you define with `--port`, 7001 by default. So it looks like it might make sense to allow it to be set with an env var. but again I don't know the best practices here. I know docker can also just do NAT, so you could be serving 7001 everywhere but just changing the ingress into docker to something else each time :shrug:

**Comment by motolies** [comment]
My understanding is that it only uses port 7001 and I can change that. 
I'll fix it tomorrow and PR it again.

**Comment by db0** [comment]
You can just push changes into this branch and it will update the PR

**Comment by motolies** [comment]
Changing the internal port doesn't require any modifications, so we've documented how to do it.

**Pull request merged**
